"use strict";
const config=window.BANNER_CONFIG||{},dialog=document.querySelector('#task-dialog'),storageKey='banner-locker-countdown-v1';
let state=null,tickId=null,successTimer=null,successShown=false;
try{const s=JSON.parse(localStorage.getItem(storageKey));if(s&&Number.isFinite(s.deadline)&&['ios','android'].includes(s.device))state=s;}catch{}
const safeUrl=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:null;}catch{return null;}};
function selectView(id){for(const p of dialog.querySelectorAll('[data-panel]'))p.classList.toggle('hidden',p.dataset.panel!==id);dialog.classList.toggle('sponsor-mode',id==='instructions');dialog.classList.toggle('provider-mode',id==='provider');}
function selectDevice(device){dialog.dataset.device=device;document.querySelector('#chosen-device').textContent=device==='android'?'Android':'iPhone / iOS';}
function openFlow(){if(state){selectDevice(state.device);selectView('instructions');showWaiting();}else selectView('device');if(!dialog.open)dialog.showModal();}
function chooseDevice(device){if(!['ios','android'].includes(device))return;selectDevice(device);selectView('instructions');}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{}}
function goToDownload(){const target=safeUrl(config.redirectUrl);if(!target)return;try{localStorage.removeItem(storageKey);}catch{}location.assign(target);}
function showCompleted(){if(successShown)return;successShown=true;clearInterval(tickId);tickId=null;selectView('instructions');if(!dialog.open)dialog.showModal();dialog.classList.add('completed-mode');document.querySelector('#sponsor-title').textContent='You’re ready!';document.querySelector('#return-status').classList.add('hidden');document.querySelector('#success-status').classList.remove('hidden');document.querySelector('#proceed-download').disabled=false;document.querySelector('#sponsor-footnote').textContent='Waiting period complete. Continue to BannerTik for the tutorial and app files.';if(typeof window.bannerCelebrate==='function')window.bannerCelebrate(dialog);let seconds=5;successTimer=setInterval(()=>{seconds--;document.querySelector('#success-seconds').textContent=String(Math.max(0,seconds));if(seconds<=0){clearInterval(successTimer);goToDownload();}},1000);}
function tick(){if(!state||successShown)return;const remaining=Math.max(0,state.deadline-Date.now()),seconds=Math.ceil(remaining/1000);const formatted=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');document.querySelector('#countdown').textContent=formatted;document.querySelector('#provider-countdown').textContent=formatted;if(remaining===0)showCompleted();}
function showWaiting(){if(successShown){selectView('instructions');return;}dialog.classList.add('waiting-mode');document.querySelector('#return-status').classList.remove('hidden');document.querySelector('#sponsor-footnote').textContent='The countdown is a waiting period, not an installation check. Complete the offer requirements before uninstalling.';document.querySelector('#open-locker').lastChild.textContent='Open Sponsor Offers Again';if(!tickId)tickId=setInterval(tick,1000);tick();}
function startSponsor(event){const url=safeUrl(config.taskUrl);if(!url||successShown){event.preventDefault();return;}event.currentTarget.href=url;if(!state){state={device:dialog.dataset.device==='android'?'android':'ios',deadline:Date.now()+(config.redirectMinutes||12)*60000};persist();}showWaiting();if(successShown){event.preventDefault();return;}if(event.currentTarget.dataset.openTab!=='true'){event.preventDefault();selectView('provider');const frame=document.querySelector('#locker-frame');if(!frame.getAttribute('src'))frame.src=url;}}
if(dialog){document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',openFlow));document.querySelectorAll('[data-choose]').forEach(b=>b.addEventListener('click',()=>chooseDevice(b.dataset.choose)));document.querySelector('#back-device').addEventListener('click',()=>selectView('device'));document.querySelector('#open-locker').addEventListener('click',startSponsor);document.querySelector('#sponsor-new-tab').addEventListener('click',startSponsor);document.querySelector('#provider-new-tab').addEventListener('click',startSponsor);document.querySelector('#back-sponsor').addEventListener('click',()=>{selectView('instructions');showWaiting();});document.querySelector('#proceed-download').addEventListener('click',()=>{if(successShown)goToDownload();});document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});if(state)openFlow();document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(state&&dialog.open)showWaiting();else tick();}});window.addEventListener('pageshow',tick);window.addEventListener('storage',e=>{if(e.key===storageKey&&e.newValue){try{const s=JSON.parse(e.newValue);if(Number.isFinite(s.deadline)&&['ios','android'].includes(s.device)){state=s;openFlow();}}catch{}}});}


